export const CometChatSettings = {
  chatFeatures: {
    coreMessagingExperience: {
      typingIndicator: true,
      threadConversationAndReplies: true,
      photosSharing: true,
      videoSharing: true,
      audioSharing: true,
      fileSharing: true,
      editMessage: true,
      deleteMessage: true,
      messageDeliveryAndReadReceipts: true,
      userAndFriendsPresence: true,
      conversationAndAdvancedSearch: true,
      moderation: true,
      quotedReplies: false,
      markAsUnread: false,
    },
    deeperUserEngagement: {
      mentions: true,
      mentionAll: true,
      reactions: true,
      messageTranslation: true,
      polls: true,
      collaborativeWhiteboard: true,
      collaborativeDocument: true,
      voiceNotes: true,
      emojis: true,
      stickers: true,
      userInfo: true,
      groupInfo: true,
    },
    aiUserCopilot: {
      conversationStarter: false,
      conversationSummary: false,
      smartReply: false,
    },
    userManagement: { friendsOnly: false },
    groupManagement: {
      createGroup: true,
      addMembersToGroups: true,
      joinLeaveGroup: true,
      deleteGroup: true,
      viewGroupMembers: true,
    },
    moderatorControls: {
      kickUsers: true,
      banUsers: true,
      promoteDemoteMembers: true,
      reportMessage: true,
    },
    privateMessagingWithinGroups: { sendPrivateMessageToGroupMembers: true },
  },
  callFeatures: {
    voiceAndVideoCalling: {
      oneOnOneVoiceCalling: true,
      oneOnOneVideoCalling: true,
      groupVideoConference: true,
      groupVoiceConference: true,
    },
  },
  layout: {
    withSideBar: true,
    tabs: ['chats', 'calls', 'users', 'groups'],
    chatType: 'user',
  },
  style: {
    theme: 'dark',
    color: {
      brandColor: '#cdfa47',
      primaryTextLight: '#141414',
      primaryTextDark: '#FFFFFF',
      secondaryTextLight: '#727272',
      secondaryTextDark: '#989898',
    },
    typography: { font: 'Inter', size: 'default' },
  },
};
